require "user.options"
require "user.plugins"

require "user.mappings"
require "user.lsp"
require "user.telescope"
require "user.custom_langs"
require "user.goodies"
require "user.tabs"
require "user.git"
require "user.snippets"
